### ISSUE TITLE
Not adding files to exclude list

### ISSUE THREAD

**Issue by 1415926535** [jcmordan/mark-as-excluded#1]
Ubuntu 16.04
This extension isn't working. I have another that toggles the excluded list and it successfully writes to the settings file. What can I check to see why this isn't working?

**Comment by jcmordan** [comment]
Some user are reporting this issue, I'm trying to figure out what is wrong, I had this on testing but then it gone without know what was happening.

**Comment by 1415926535** [comment]
Killer extension idea. Let me know if I can help. I'll test on my other Xenial machine and see if it's the same there.

**Comment by 1415926535** [comment]
It's not working on my other Ubu 16.04 machine either, and I don't keep them identical. The machine I'm on now is a two week old install. The [Peep](https://marketplace.visualstudio.com/items?itemName=nwallace.peep) ext works. It just toggles the exclude list. Maybe something in that [repo](https://github.com/natewallace/peep) will give you a clue. This stuff is over my head so it would take me a week or more to figure out how extensions work.

**Comment by jcmordan** [comment]
I think I found the solution, the problem is that the file settting.json  do not exist in the .vscode folder. the file must be there and must have a least an empty brackets. 

`{}`

I will fix it, creating the the file if do not exist!

**Comment by 1415926535** [comment]
When I first tried the extension I had not created a workspace settings file yet, so I thought that was the problem too. I then created the file by adding the default excludes to it, uninstalled and reinstalled extension and still nothing. Maybe your extension works on Windows and Macs but not Ubuntu or something, thus being a permissions issue?? Just a guess. You know way more about this stuff than I do.

**Comment by jcmordan** [comment]
I've developed and tested the extension on windows, but yesterday I was on ubuntu and creating the settings.json file on the workpaces works for me. 

It's hard to figure out what going on since the extension does not show any error. just does not do it job.

**Comment by 1415926535** [comment]
I just purged vscode from my machine and reinstalled. It didn't help. I'm going to do one more time because I didn't delete the extensions folder. 

OK. I just uninstalled and deleted .config/Code and .vscode. Rebooted and reinstalled. Add only your extenstion and still no worky worky. I created the vscode settings file before installing extension. 

I give up for now. I need to get back to work.

**Comment by jcmordan** [comment]
Hello, I had published a new version, had you tried it?

**Comment by 1415926535** [comment]
Trying now.

**Comment by 1415926535** [comment]
Worked instantly! Thanks so much. Now using yours and the Peep extension vscode has something I've always wanted but never had. (not saying it doesn't exist elsewhere but I never had this setup on other editors). 

Thanks for time and effort big time!

**Comment by jcmordan** [comment]
@1415926535 Tanks you for use my extension and help me improve it. 

> (not saying it doesn't exist elsewhere but I never had this setup on other editors).

To be honest I get inspiration from Intellij, I'm moving to vscode because lightness and free.

**Comment by 1415926535** [comment]
Man, I click back and forth between it and atom. As soon as I get comfortable with one, I want to switch to compare them again. I'm new at all this so still feeling my way around in the dark a little.

**Comment by 1415926535** [comment]
UPDATE: After you fixed it last time, it only worked sometimes. Well I had other issues with my machine and literally fixed my machine to death. Sooo then I wiped my OS reinstalled everything. Not sure if that fixed the issue with your extension but signs point to 'yes.' It's working like you and I both want it to work now. So my problems AFTER you fixed it for me above was highly likely to be on my end. 

Again, thanks for your time in creating this extension.

**Comment by jcmordan** [comment]
Nice, then your are not getting errors any more?

Thanks you for using it and spend your time reporting bugs.
