### ISSUE TITLE
Error: The file could not be excluded, verify you have access

### ISSUE THREAD

**Issue by tnrich** [jcmordan/mark-as-excluded#2]
![image](https://user-images.githubusercontent.com/2730609/29292045-a911a040-8113-11e7-98f4-77070a01493c.png)

I get this when trying to mark my dist/ folder. Any thoughts?

I really want this to work!

Thanks!

**Comment by jcmordan** [comment]
Can you give me more details:

vscode version:
extention version:
OS:

Thanks.

**Comment by tnrich** [comment]
Version 1.15.0 (1.15.0)

Latest extension version.

mac os

**Comment by 1415926535** [comment]
Does it do it on other folders or just dist/?
If it doesn't work at all it's likely a perm issue with writing to the settings array for the workspace. And I would even guess you're excluding using your **User Settings** and not **Workspace Settings**. Can you verify your workspace settings array has the `"files.exclude":` statement already. I think this extension will NOT create that statement if it's not already present but not completely sure. 

The directions point to workspace with this statement. 
`Menu: Mark as excluded: Add the selected file/folder to the files.exlude list in the ~/.vscode/settings.json file. It won't be appear in the file explorer.`

**Comment by jcmordan** [comment]
@tnrich 

Hello, I exclude using the Workspace Settings, I had tested the extension looking the  Workspace Settings file.

In the latest version the extension is trying to create the file if is not present in your  Workspace Settings, but since the first version it create the "files.exclude": session if not there.

 I hadn't tested the extention on Mac OS, just Ubuntu and Windows. Can you try running vscode with elevated persimisons.

**Comment by tnrich** [comment]
@jcmordan Hmm it seems to be working for me now. I'm not sure what changed. I was also seeing an issue with the glob pattern failing but can't reproduce that right now either. Curious.. If I see it again I'll let you know and take a little video. 

Cheers!

**Comment by tnrich** [comment]
Whoops, I take that back. Here is the issue I'm still seeing: 

<img width="1440" alt="screen shot 2017-08-30 at 10 21 17 am" src="https://user-images.githubusercontent.com/2730609/29882011-d55e1fee-8d79-11e7-9760-963c4911a672.png">

**Comment by jcmordan** [comment]
That sould work. but this error is on the Search panel.

What happend when you clicked the **Mark as excluded** option?

What happend when you clicked the **Ignore for search** option?

**Comment by tnrich** [comment]
So the line: 

`"**dist": true` 

is added when I hit **Ignore from Search** or **Mark as excluded** on the dist folder to the correct location in the workspace setting file. That part is working fine it seems. 

I think the issue here is just that the glob pattern that is getting inserted: `**dist` is invalid ?

**Comment by jcmordan** [comment]
The pattern is valid, you cand edit the entry manually

changing it for this:  "**/dist": true, and the result should be the same.

Note:
**Mark as excluded** option add an entry on `file.excludes: {}` and the file or folder must desapear from the tree vew.

**Exclude from search** option add an entry on `search.exclude: {}` and the file or folder do not desapear from the tree view.

**Comment by ryan-surrey** [comment]
I saw this same error if I hadn't previously edited the settings for the workspace, it seems its because the .vscode/settings.json file doesn't exist until you go to File-->Preferneces-->Settings for the first time
