### ISSUE TITLE
Wrong settings.json updated in multi-root workspace

### ISSUE THREAD

**Issue by ryan-surrey** [jcmordan/mark-as-excluded#3]
If you have a workspace with more than one folder added to it, the exclude paths are all added to the first folders settings.json file, and hence are not excluded correctly.

The screenshot below shows the excludes from the two different folders being added to the first folders exclude list, and hence exclude_me_b folder is still visible.

![image](https://user-images.githubusercontent.com/6798534/43084003-b61335d0-8e8f-11e8-8165-9b3b92281266.png)

**Comment by ngocphamm** [comment]
Can confirm this!

**Comment by jcmordan** [comment]
Hello, sorry I wasn't available to work on this project, but I will be working on this issue in the next days.

**Comment by ngocphamm** [comment]
Not a problem at all buddy. Thank you for a useful extension!!!

**Comment by jcmordan** [comment]
fixed on v 0.2.6
